version: '2'

services:
  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/development:/etc/nginx/conf.d
    networks:
      - wordnetwork
    depends_on:
      - backend
      - frontend
  backend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - wordnetwork
    entrypoint: /app/docker/backend/wsgi-entrypoint.sh
    expose:
      - 8000
  frontend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    volumes:
      - frontend:/app/build
    command: sh -c "npm install && npm run build"
networks:
  wordnetwork:
    driver: bridge
volumes:
  frontend:
  backend: