version: '2'

services:
  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/development:/etc/nginx/conf.d
    networks:
      - wordnetwork
    depends_on:
      - backend
  backend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .test.env
    networks:
      - wordnetwork
    entrypoint: /app/docker/backend/wsgi-entrypoint.sh
    expose:
      - 8000
networks:
  wordnetwork:
    driver: bridge
volumes:
  backend: